spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      default:  #默认数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.101.110:3306/ssm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: 123456
      first:  #数据源1
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.101.110:3306/ssm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: 123456
      second:  #数据源2
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.101.110:3306/ssm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
      credit:  #数据源3
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.101.110:3306/ssm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
      filter:
        slf4j:
          enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false
        #isolation = Isolation.READ_COMMITTED,propagation = Propagation.REQUIRED
    #   数据源其他配置
    initialSize: 10
    minIdle: 10
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  resources:
    static-locations: classpath:/static/  #在这里表示配置静态资源根路径
  mvc:
    view:
      #采用jsp模板引擎
      #prefix: /WEB-INF/jsp/
      prefix: classpath:/templates/
      #suffix: .jsp
      suffix: .html
    static-path-pattern: /**   #/**表示所有的访问都经过静态资源路径
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

    chain:
      cache: false
  #thymeleaf配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    #网页路径
    prefix: classpath:/templates/   #在这里作为前缀，表示被thymeleaf修饰的页面在这里作为根目录
    suffix: .html  # 在这里表示以.html作为后缀
  #ehcache 多个用逗号分开
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
    #redis
  redis:
    host: localhost
    port: 6379
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#  schema:
#  - classpath:sql/department.sql
#  - classpath:sql/employee.sql

#服务端口配置
server:
  port: 8080

  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
  management:
    port: 54001
    health:
      mail:
        enabled: false

  servlet:
    session:
      timeout: 3000s
    context-path: /


  #极光推送配置
jpush:
  isDebug: false #是否测试环境
  appKey: 123
  masterSecret: 123
  liveTime: 86400 #离线信息保存时间60*60*24
  #阿里云短信配置
aliyun:
  AccessKeyID: 123
  AccessKeySecret: 123
  #mybatis打印SQL语句
#logging:
#  level:
    #定义需要打印SQL语句的包
   # cn.qxl.Mapper: debug




